package com.event.prototype.data.entity;

import com.event.prototype.data.enums.DefaultPicture;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.Type;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Index;
import javax.persistence.Table;

@Entity
@Table(name = "pictures", indexes = {
        @Index(columnList = "default_type")
})
@Getter
@Setter
@NoArgsConstructor
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class Picture extends AbstractAutoGeneratedIdEntity {

    @Type(type = "org.hibernate.type.BinaryType")
    @Column(name = "source_pic")
    @NonNull
    private byte[] sourcePic;

    @Type(type = "org.hibernate.type.BinaryType")
    @Column(name = "small_pic")
    @NonNull
    private byte[] smallPic;

    @Column(name = "default_type", length = 50)
    @Enumerated(EnumType.STRING)
    private DefaultPicture defaultPicture;

    @Column(name = "mime_type", length = 100)
    @NonNull
    private String mimeType;

    public Picture(Long id) {
        super(id);
    }

    public Picture(byte[] sourcePic, byte[] smallPic, DefaultPicture defaultPicture) {
        this.sourcePic = sourcePic;
        this.smallPic = smallPic;
        this.defaultPicture = defaultPicture;
    }
}
